In [1]:
#importing the necessary libraries
import pandas as pd
import numpy as np

In [2]:
#data reading
data=pd.read_csv('C:/Users/F/Downloads/googleplaystore.csv/googleplaystore.csv')
data.head()

App        Category  Rating  \
0     Photo Editor & Candy Camera & Grid & ScrapBook  ART_AND_DESIGN     4.1   
1                                Coloring book moana  ART_AND_DESIGN     3.9   
2  U Launcher Lite – FREE Live Cool Themes, Hide ...  ART_AND_DESIGN     4.7   
3                              Sketch - Draw & Paint  ART_AND_DESIGN     4.5   
4              Pixel Draw - Number Art Coloring Book  ART_AND_DESIGN     4.3   

  Reviews  Size     Installs  Type Price Content Rating  \
0     159   19M      10,000+  Free     0       Everyone   
1     967   14M     500,000+  Free     0       Everyone   
2   87510  8.7M   5,000,000+  Free     0       Everyone   
3  215644   25M  50,000,000+  Free     0           Teen   
4     967  2.8M     100,000+  Free     0       Everyone   

                      Genres      Last Updated         Current Ver  \
0               Art & Design   January 7, 2018               1.0.0   
1  Art & Design;Pretend Play  January 15, 2018               2.0.0   
2               Art & Design    August 1, 2018               1.2.4   
3               Art & Design      June 8, 2018  Varies with device   
4    Art & Design;Creativity     June 20, 2018                 1.1   

    Android Ver  
0  4.0.3 and up  
1  4.0.3 and up  
2  4.0.3 and up  
3    4.2 and up  
4    4.4 and up

In [3]:
#checking for missing values
print(data.isnull().sum())

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64


In [4]:
#as we can see, there are very few missing values in the dataset, 
#so we can delete rows with them without changing the missing values with other values
data.dropna(how='any', inplace=True)

In [5]:
data.isnull().sum()

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    0
Genres            0
Last Updated      0
Current Ver       0
Android Ver       0
dtype: int64

In [6]:
#shape of data
data.shape

(9360, 13)

In [7]:
#number of unique values of 'App' feature
data['App'].nunique()

8190

In [8]:
#number of duplicate values of 'App' feature
data.duplicated(subset=['App']).sum()

1170

In [9]:
#here we see several rows that have a duplicate based on the 'App' feature
data[data.duplicated(subset=['App'], keep='first')].head(10)

App  Category  Rating Reviews  \
229  Quick PDF Scanner + OCR FREE  BUSINESS     4.2   80805   
236                           Box  BUSINESS     4.2  159872   
239            Google My Business  BUSINESS     4.4   70991   
256           ZOOM Cloud Meetings  BUSINESS     4.4   31614   
261     join.me - Simple Meetings  BUSINESS     4.0    6989   
265                           Box  BUSINESS     4.2  159872   
266                      Zenefits  BUSINESS     4.2     296   
267                    Google Ads  BUSINESS     4.3   29313   
268            Google My Business  BUSINESS     4.4   70991   
269                         Slack  BUSINESS     4.4   51507   

                   Size     Installs  Type Price Content Rating    Genres  \
229  Varies with device   5,000,000+  Free     0       Everyone  Business   
236  Varies with device  10,000,000+  Free     0       Everyone  Business   
239  Varies with device   5,000,000+  Free     0       Everyone  Business   
256                 37M  10,000,000+  Free     0       Everyone  Business   
261  Varies with device   1,000,000+  Free     0       Everyone  Business   
265  Varies with device  10,000,000+  Free     0       Everyone  Business   
266                 14M      50,000+  Free     0       Everyone  Business   
267                 20M   5,000,000+  Free     0       Everyone  Business   
268  Varies with device   5,000,000+  Free     0       Everyone  Business   
269  Varies with device   5,000,000+  Free     0       Everyone  Business   

          Last Updated         Current Ver         Android Ver  
229  February 26, 2018  Varies with device        4.0.3 and up  
236      July 31, 2018  Varies with device  Varies with device  
239      July 24, 2018    2.19.0.204537701          4.4 and up  
256      July 20, 2018      4.1.28165.0716          4.0 and up  
261      July 16, 2018           4.3.0.508          4.4 and up  
265      July 31, 2018  Varies with device  Varies with device  
266      June 15, 2018               3.2.1          4.1 and up  
267      July 30, 2018              1.12.0        4.0.3 and up  
268      July 24, 2018    2.19.0.204537701          4.4 and up  
269     August 2, 2018  Varies with device  Varies with device

In feature engineering, the first thing that comes to mind is removing duplicate features. But we checked for duplicate features based on a feature 'App', while the rest of the features of these rows may be different(although it is logical that the same application has the same parameters). Therefore we must check this by comparing duplicates of at least one row that has duplicates. For example, 'Box' If all the features match, then we have to remove the duplicates, leaving only the first of them.

In [10]:
#compare duplicates
data[data['App']=='Box']

App  Category  Rating Reviews                Size     Installs  Type  \
204  Box  BUSINESS     4.2  159872  Varies with device  10,000,000+  Free   
236  Box  BUSINESS     4.2  159872  Varies with device  10,000,000+  Free   
265  Box  BUSINESS     4.2  159872  Varies with device  10,000,000+  Free   

    Price Content Rating    Genres   Last Updated         Current Ver  \
204     0       Everyone  Business  July 31, 2018  Varies with device   
236     0       Everyone  Business  July 31, 2018  Varies with device   
265     0       Everyone  Business  July 31, 2018  Varies with device   

            Android Ver  
204  Varies with device  
236  Varies with device  
265  Varies with device

In [11]:
#removing duplicate rows
data.drop_duplicates(keep='first', inplace=True)

In [12]:
#as you can see, we have kept the basic row
data[data['App']=='Box']

App  Category  Rating Reviews                Size     Installs  Type  \
204  Box  BUSINESS     4.2  159872  Varies with device  10,000,000+  Free   

    Price Content Rating    Genres   Last Updated         Current Ver  \
204     0       Everyone  Business  July 31, 2018  Varies with device   

            Android Ver  
204  Varies with device

In [13]:
#unique values of 'Category' feature
data['Category'].unique()

array(['ART_AND_DESIGN', 'AUTO_AND_VEHICLES', 'BEAUTY',
       'BOOKS_AND_REFERENCE', 'BUSINESS', 'COMICS', 'COMMUNICATION',
       'DATING', 'EDUCATION', 'ENTERTAINMENT', 'EVENTS', 'FINANCE',
       'FOOD_AND_DRINK', 'HEALTH_AND_FITNESS', 'HOUSE_AND_HOME',
       'LIBRARIES_AND_DEMO', 'LIFESTYLE', 'GAME', 'FAMILY', 'MEDICAL',
       'SOCIAL', 'SHOPPING', 'PHOTOGRAPHY', 'SPORTS', 'TRAVEL_AND_LOCAL',
       'TOOLS', 'PERSONALIZATION', 'PRODUCTIVITY', 'PARENTING', 'WEATHER',
       'VIDEO_PLAYERS', 'NEWS_AND_MAGAZINES', 'MAPS_AND_NAVIGATION'],
      dtype=object)

In [14]:
#one-hot encoding of 'Category' feature
data=pd.get_dummies(data, columns=['Category'])

In [15]:
#unique features are created in the dataset for each value of 'Category' feature
data.columns

Index(['App', 'Rating', 'Reviews', 'Size', 'Installs', 'Type', 'Price',
       'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver', 'Category_ART_AND_DESIGN', 'Category_AUTO_AND_VEHICLES',
       'Category_BEAUTY', 'Category_BOOKS_AND_REFERENCE', 'Category_BUSINESS',
       'Category_COMICS', 'Category_COMMUNICATION', 'Category_DATING',
       'Category_EDUCATION', 'Category_ENTERTAINMENT', 'Category_EVENTS',
       'Category_FAMILY', 'Category_FINANCE', 'Category_FOOD_AND_DRINK',
       'Category_GAME', 'Category_HEALTH_AND_FITNESS',
       'Category_HOUSE_AND_HOME', 'Category_LIBRARIES_AND_DEMO',
       'Category_LIFESTYLE', 'Category_MAPS_AND_NAVIGATION',
       'Category_MEDICAL', 'Category_NEWS_AND_MAGAZINES', 'Category_PARENTING',
       'Category_PERSONALIZATION', 'Category_PHOTOGRAPHY',
       'Category_PRODUCTIVITY', 'Category_SHOPPING', 'Category_SOCIAL',
       'Category_SPORTS', 'Category_TOOLS', 'Category_TRAVEL_AND_LOCAL',
       'Category_VIDE

In [16]:
#unique values of 'Rating' feature
data['Rating'].unique()

array([4.1, 3.9, 4.7, 4.5, 4.3, 4.4, 3.8, 4.2, 4.6, 4. , 4.8, 4.9, 3.6,
       3.7, 3.2, 3.3, 3.4, 3.5, 3.1, 5. , 2.6, 3. , 1.9, 2.5, 2.8, 2.7,
       1. , 2.9, 2.3, 2.2, 1.7, 2. , 1.8, 2.4, 1.6, 2.1, 1.4, 1.5, 1.2])

In [17]:
#unique values of 'Reviews' feature
data['Reviews'].unique()

array(['159', '967', '87510', ..., '603', '1195', '398307'], dtype=object)

In [18]:
#as we see values of 'Reviews' feature has object type, so we have to change its type   
data['Reviews']=data['Reviews'].astype(int)

In [19]:
data['Reviews'].unique()

array([   159,    967,  87510, ...,    603,   1195, 398307])

In [20]:
#unique values of 'Size' feature
data['Size'].unique()

array(['19M', '14M', '8.7M', '25M', '2.8M', '5.6M', '29M', '33M', '3.1M',
       '28M', '12M', '20M', '21M', '37M', '5.5M', '17M', '39M', '31M',
       '4.2M', '23M', '6.0M', '6.1M', '4.6M', '9.2M', '5.2M', '11M',
       '24M', 'Varies with device', '9.4M', '15M', '10M', '1.2M', '26M',
       '8.0M', '7.9M', '56M', '57M', '35M', '54M', '201k', '3.6M', '5.7M',
       '8.6M', '2.4M', '27M', '2.7M', '2.5M', '7.0M', '16M', '3.4M',
       '8.9M', '3.9M', '2.9M', '38M', '32M', '5.4M', '18M', '1.1M',
       '2.2M', '4.5M', '9.8M', '52M', '9.0M', '6.7M', '30M', '2.6M',
       '7.1M', '22M', '6.4M', '3.2M', '8.2M', '4.9M', '9.5M', '5.0M',
       '5.9M', '13M', '73M', '6.8M', '3.5M', '4.0M', '2.3M', '2.1M',
       '42M', '9.1M', '55M', '23k', '7.3M', '6.5M', '1.5M', '7.5M', '51M',
       '41M', '48M', '8.5M', '46M', '8.3M', '4.3M', '4.7M', '3.3M', '40M',
       '7.8M', '8.8M', '6.6M', '5.1M', '61M', '66M', '79k', '8.4M',
       '3.7M', '118k', '44M', '695k', '1.6M', '6.2M', '53M', '1.4M',
      

Here we see the letters 'k' and 'M' after the numbers. These are kilobytes and Megabytes, and we have to convert them all to bytes. Also we have to change the value 'Varies with device' to the mean value of the column.

In [21]:
#firstly we have to change 'Varies with device' with 0
data['Size'].replace('Varies with device', 0 , inplace = True ) 

In [22]:
# translate values to bytes
data['Size'].replace({'k':'*1000', 'M':'*1000000'}, regex=True, inplace=True)
data['Size']=data['Size'].apply(pd.eval).astype(float)

In [23]:
# change 0 to mean
mean=round(data['Size'].mean())
data['Size'].replace(0, mean, inplace=True)

In [24]:
#unique values of 'Installs' feature
data['Installs'].unique()

array(['10,000+', '500,000+', '5,000,000+', '50,000,000+', '100,000+',
       '50,000+', '1,000,000+', '10,000,000+', '5,000+', '100,000,000+',
       '1,000,000,000+', '1,000+', '500,000,000+', '100+', '500+', '10+',
       '5+', '50+', '1+'], dtype=object)

In [25]:
# we have to round the values by removing the '+' and convert them to a numeric value
data['Installs'] = data['Installs'].apply(lambda x : x.strip('+').replace(',', '')).astype(float)

In [26]:
data['Installs'].head()

0       10000.0
1      500000.0
2     5000000.0
3    50000000.0
4      100000.0
Name: Installs, dtype: float64

In [27]:
#unique values of 'Type' feature
data['Type'].unique()

array(['Free', 'Paid'], dtype=object)

In [28]:
# the 'Type' feature has two values so we can encode it with binary code
from sklearn.preprocessing import LabelBinarizer

In [29]:
binarizer=LabelBinarizer()
data['Type']=binarizer.fit_transform(data.Type)
data['Type'].unique()

array([0, 1])

In [30]:
#unique values of 'Price' feature
data['Price'].unique()

array(['0', '$4.99', '$3.99', '$6.99', '$7.99', '$5.99', '$2.99', '$3.49',
       '$1.99', '$9.99', '$7.49', '$0.99', '$9.00', '$5.49', '$10.00',
       '$24.99', '$11.99', '$79.99', '$16.99', '$14.99', '$29.99',
       '$12.99', '$2.49', '$10.99', '$1.50', '$19.99', '$15.99', '$33.99',
       '$39.99', '$3.95', '$4.49', '$1.70', '$8.99', '$1.49', '$3.88',
       '$399.99', '$17.99', '$400.00', '$3.02', '$1.76', '$4.84', '$4.77',
       '$1.61', '$2.50', '$1.59', '$6.49', '$1.29', '$299.99', '$379.99',
       '$37.99', '$18.99', '$389.99', '$8.49', '$1.75', '$14.00', '$2.00',
       '$3.08', '$2.59', '$19.40', '$3.90', '$4.59', '$15.46', '$3.04',
       '$13.99', '$4.29', '$3.28', '$4.60', '$1.00', '$2.95', '$2.90',
       '$1.97', '$2.56', '$1.20'], dtype=object)

In [31]:
# we have to remove the '$' and convert them to a numeric value
data['Price']=data['Price'].apply(lambda x : x.replace('$', '')).astype(float)
data['Price'].unique()

array([  0.  ,   4.99,   3.99,   6.99,   7.99,   5.99,   2.99,   3.49,
         1.99,   9.99,   7.49,   0.99,   9.  ,   5.49,  10.  ,  24.99,
        11.99,  79.99,  16.99,  14.99,  29.99,  12.99,   2.49,  10.99,
         1.5 ,  19.99,  15.99,  33.99,  39.99,   3.95,   4.49,   1.7 ,
         8.99,   1.49,   3.88, 399.99,  17.99, 400.  ,   3.02,   1.76,
         4.84,   4.77,   1.61,   2.5 ,   1.59,   6.49,   1.29, 299.99,
       379.99,  37.99,  18.99, 389.99,   8.49,   1.75,  14.  ,   2.  ,
         3.08,   2.59,  19.4 ,   3.9 ,   4.59,  15.46,   3.04,  13.99,
         4.29,   3.28,   4.6 ,   1.  ,   2.95,   2.9 ,   1.97,   2.56,
         1.2 ])

In [32]:
#unique values of 'Content Rating' feature
data['Content Rating'].unique()

array(['Everyone', 'Teen', 'Everyone 10+', 'Mature 17+',
       'Adults only 18+', 'Unrated'], dtype=object)

In [33]:
# if 'Unrated' rows are few, then we can just delete them instead of encoding
data[data['Content Rating']=='Unrated']

App  Rating  Reviews       Size  Installs  Type  \
8266  DC Universe Online Map     4.1     1186  6400000.0   50000.0     0   

      Price Content Rating Genres       Last Updated  ...  \
8266    0.0        Unrated  Tools  February 27, 2012  ...   

     Category_PERSONALIZATION Category_PHOTOGRAPHY  Category_PRODUCTIVITY  \
8266                        0                    0                      0   

      Category_SHOPPING  Category_SOCIAL  Category_SPORTS  Category_TOOLS  \
8266                  0                0                0               1   

      Category_TRAVEL_AND_LOCAL  Category_VIDEO_PLAYERS  Category_WEATHER  
8266                          0                       0                 0  

[1 rows x 45 columns]

In [34]:
#removing one row
data=data.drop(index=8266)
data['Content Rating'].unique()

array(['Everyone', 'Teen', 'Everyone 10+', 'Mature 17+',
       'Adults only 18+'], dtype=object)

Feature 'Content Rating' has ordinal values, so we can encode its values with numbers from 1 to n. We can encode them in order of increasing number of consumers(in order of decreasing restrictions).

In [35]:
data['Content Rating']=data['Content Rating'].replace({'Adults only 18+':1, 'Mature 17+':2, 'Teen':3, 'Everyone 10+':4, 'Everyone':5 })
data['Content Rating'].unique()

array([5, 3, 4, 2, 1], dtype=int64)

In [36]:
# the feature 'App' acts as an identifier so we can remove it
# other features do not really matter when training the model, so they can also be deleted
data.drop(['App', 'Genres', 'Last Updated', 'Current Ver', 'Android Ver'], axis=1, inplace=True)

In [37]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8885 entries, 0 to 10840
Data columns (total 40 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Rating                        8885 non-null   float64
 1   Reviews                       8885 non-null   int32  
 2   Size                          8885 non-null   float64
 3   Installs                      8885 non-null   float64
 4   Type                          8885 non-null   int32  
 5   Price                         8885 non-null   float64
 6   Content Rating                8885 non-null   int64  
 7   Category_ART_AND_DESIGN       8885 non-null   uint8  
 8   Category_AUTO_AND_VEHICLES    8885 non-null   uint8  
 9   Category_BEAUTY               8885 non-null   uint8  
 10  Category_BOOKS_AND_REFERENCE  8885 non-null   uint8  
 11  Category_BUSINESS             8885 non-null   uint8  
 12  Category_COMICS               8885 non-null   uint8  
 13  Ca